<a href="https://colab.research.google.com/github/cirobezerradev/projeto-tecfor-industrial/blob/main/An%C3%A1lise_de_Dados_Industriais.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Análise de dados Industriais

#### Importações

In [ ]:
import pandas as pd
import numpy as np
from datetime import datetime

### Extração e Tratamento dos dados sensores.json

In [ ]:
df_sensores = pd.read_json('/content/sensores.json')
df_medicoes = pd.DataFrame(dict(df_sensores['medicoes'])).T

df_sensores = df_sensores.drop(columns=['medicoes'], axis=1)

df_sensores = pd.concat([df_sensores, df_medicoes], axis=1)

# O df_sensores apresentou inconsistencia na quantidade de registro da serie 'temperaturas'
# Etapa 1 verificar a quantidade de registos nulos
# print(df_sensores.isna().sum())
# Verificado 6 registros nulos
# Etapa 2 substituir os valores nulos pela mediana
df_sensores['temperatura'] = df_sensores['temperatura'].fillna(df_sensores['temperatura'].median())

# Verificar duplicados
print(f'Duplicados: {df_sensores.duplicated().sum()}')
# verificado 4 duplicados
# Etapa 3 excluir duplicados
df_sensores = df_sensores.drop_duplicates()
# converter para datetime e padronizar o formato para futuro merge
df_sensores['timestamp'] = pd.to_datetime(df_sensores['timestamp']).dt.strftime('%Y-%m-%d')
# renomear a coluna timestamp para data
df_sensores = df_sensores.rename(columns={'timestamp': 'data'})

df_sensores

Duplicados: 4

,id_maquina,data,status,consumo_energia,temperatura,vibracao,pressao,velocidade
0,MAQ-03,2025-03-20,operando,11.86,68.1,2.32,5.93,1288.8
1,MAQ-10,2025-03-24,operando,13.89,60.4,1.91,4.49,1020.1
2,MAQ-10,2025-03-23,operando,9.88,65.5,2.08,4.24,1181.3
3,MAQ-02,2025-03-04,operando,13.63,66.4,2.36,5.34,1153.6
4,MAQ-07,2025-03-24,operando,14.98,70.5,2.77,5.73,1155.1
...,...,...,...,...,...,...,...,...
609,MAQ-02,2025-03-09,operando,11.03,68.3,2.20,5.66,1289.3
610,MAQ-03,2025-03-27,operando,15.25,70.1,1.88,5.68,1158.5
611,MAQ-07,2025-03-19,operando,10.36,64.8,1.89,6.01,1276.7
612,MAQ-08,2025-03-21,operando,13.10,65.5,3.20,4.43,1169.6
613,MAQ-09,2025-03-04,operando,10.74,64.0,2.69,5.32,1088.6

### Extracao e Tratamento dos dados producao.csv

In [ ]:
df_producao = pd.read_csv('/content/producao.csv')

# Etapa 1 Verificar dados nulos
# print(df_producao.isna().sum())
# identificado valores nulos na 'quantidade_produzida', 'tempo_producao' e 'operador'
# Substituir valores nulos de 'quantidade_produzida', 'tempo_producao' pela mediana
df_producao['quantidade_produzida'] = df_producao['quantidade_produzida']\
                .fillna(df_producao['quantidade_produzida'].median())
df_producao['tempo_producao'] = df_producao['tempo_producao']\
                .fillna(df_producao['tempo_producao'].median())
# Substituir valores nulos de 'operador' pela mediana
df_producao['operador'] = df_producao['operador']\
                .fillna(df_producao['operador'].mode()[0])

# Etapa 2 Verificar Duplicados
# print(df_producao.duplicated().sum())
# Localizado 5 valores duplciados
df_producao = df_producao.drop_duplicates()
# Convertendo data para datetime e padronizando o formato
df_producao['data'] = pd.to_datetime(df_producao['data'], yearfirst=True, format='mixed')

df_producao['maquina'] = df_producao['maquina'].str.strip().str.upper().str.replace('  ', ' ')
# df_producao['maquina'] =

# df_producao['maquina'] = df_producao['maquina'].str.replace('1', '01').str.replace('2', '02').str.replace('00', '0')
df_producao['maquina'].unique()

0              EXTRUSORA 01
1      PRENSA HIDRÁULICA 02
2              EXTRUSORA 01
3              FRESADORA 01
4       SOLDA ROBOTIZADA 02
               ...
341            EXTRUSORA 01
342            TORNO CNC 02
343    PRENSA HIDRÁULICA 01
344     SOLDA ROBOTIZADA 02
345            FRESADORA 01
Name: maquina, Length: 341, dtype: object